# Generated by Django 5.1.4 on 2025-10-25 18:55

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0014_mark_linked_cost_types'),
        ('invoices', '0020_invoice_estado_pago_invoice_monto_pagado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('fecha_pago', models.DateField(help_text='Fecha en que se realizó el pago/transferencia')),
                ('monto_total', models.DecimalField(decimal_places=2, help_text='Monto total de la transferencia o pago', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('referencia', models.CharField(blank=True, help_text='Número de referencia, ID de transferencia, etc.', max_length=100)),
                ('archivo_comprobante', models.FileField(blank=True, help_text='Comprobante de pago (PDF, imagen)', null=True, upload_to='supplier_payments/')),
                ('notas', models.TextField(blank=True, help_text='Notas internas')),
                ('proveedor', models.ForeignKey(help_text='Proveedor al que se realizó el pago', on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payments', to='catalogs.provider')),
                ('registrado_por', models.ForeignKey(blank=True, help_text='Usuario que registró el pago', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_supplier_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago a Proveedor',
                'verbose_name_plural': 'Pagos a Proveedores',
                'db_table': 'supplier_payments',
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.CreateModel(
            name='SupplierPaymentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monto_pagado_factura', models.DecimalField(decimal_places=2, help_text='Cuánto de este pago se asigna a esta factura específica', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('cost_invoice', models.ForeignKey(help_text='Factura de costo que se está pagando', on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payment_links', to='invoices.invoice')),
                ('supplier_payment', models.ForeignKey(help_text='Pago al que pertenece este link', on_delete=django.db.models.deletion.CASCADE, related_name='invoice_links', to='supplier_payments.supplierpayment')),
            ],
            options={
                'verbose_name': 'Link de Pago a Factura',
                'verbose_name_plural': 'Links de Pago a Facturas',
                'db_table': 'supplier_payment_links',
            },
        ),
        migrations.AddIndex(
            model_name='supplierpayment',
            index=models.Index(fields=['-fecha_pago'], name='supplier_pa_fecha_p_b83eab_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierpayment',
            index=models.Index(fields=['proveedor', '-fecha_pago'], name='supplier_pa_proveed_6a2179_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierpaymentlink',
            index=models.Index(fields=['supplier_payment'], name='supplier_pa_supplie_f364db_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierpaymentlink',
            index=models.Index(fields=['cost_invoice'], name='supplier_pa_cost_in_0124a4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='supplierpaymentlink',
            unique_together={('supplier_payment', 'cost_invoice')},
        ),
    ]
