# Generated by Django 5.1.4 on 2025-10-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(help_text='Nombre del proveedor', max_length=255, unique=True)),
                ('nit', models.CharField(blank=True, help_text='NIT del proveedor', max_length=20, null=True, unique=True)),
                ('tipo', models.CharField(choices=[('naviera', 'Naviera'), ('agente_local', 'Agente Local'), ('transportista', 'Transportista'), ('otro', 'Otro')], default='otro', help_text='Tipo de proveedor', max_length=20)),
                ('categoria', models.CharField(choices=[('internacional', 'Internacional'), ('nacional', 'Nacional'), ('regional', 'Regional')], default='nacional', help_text='Categoría del proveedor', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Email principal del proveedor', max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, help_text='Teléfono de contacto', max_length=20, null=True)),
                ('direccion', models.TextField(blank=True, help_text='Dirección física', null=True)),
                ('contacto', models.CharField(blank=True, help_text='Nombre de la persona de contacto', max_length=255, null=True)),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre el proveedor', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el proveedor está activo')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'catalogs_provider',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['tipo', 'is_active'], name='catalogs_pr_tipo_ba2f02_idx'), models.Index(fields=['categoria', 'is_active'], name='catalogs_pr_categor_b24a5b_idx'), models.Index(fields=['nombre'], name='catalogs_pr_nombre_099997_idx')],
            },
        ),
    ]
