# Generated by Django 5.1.4 on 2025-10-06 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='dias_credito',
            field=models.PositiveIntegerField(default=0, help_text='Días de crédito otorgados por el proveedor'),
        ),
        migrations.AddField(
            model_name='provider',
            name='notas_credito',
            field=models.TextField(blank=True, help_text='Notas adicionales sobre términos de crédito y pago', null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='payment_terms',
            field=models.TextField(blank=True, help_text="Términos y condiciones de pago (ej: '30 días desde fecha de factura')", null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='tiene_credito',
            field=models.BooleanField(default=False, help_text='Indica si el proveedor ofrece términos de crédito'),
        ),
    ]
