# Generated by Django 5.1.4 on 2025-10-10 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0002_provider_dias_credito_provider_notas_credito_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(help_text='Código único del tipo de costo (ej: FLETE, TRANSPORTE)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Nombre descriptivo del tipo de costo', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Descripción detallada del tipo de costo', null=True)),
                ('category', models.CharField(choices=[('maritimo', 'Marítimo'), ('terrestre', 'Terrestre'), ('aduanal', 'Aduanal'), ('almacenaje', 'Almacenaje'), ('otro', 'Otro')], default='otro', help_text='Categoría del tipo de costo', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el tipo de costo está activo')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Orden de visualización (menor número aparece primero)')),
            ],
            options={
                'verbose_name': 'Tipo de Costo',
                'verbose_name_plural': 'Tipos de Costo',
                'db_table': 'catalogs_cost_type',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['code'], name='catalogs_co_code_d53a8c_idx'), models.Index(fields=['category', 'is_active'], name='catalogs_co_categor_285528_idx'), models.Index(fields=['display_order'], name='catalogs_co_display_7caa4b_idx')],
            },
        ),
    ]
