# Generated by Django 5.1.4 on 2025-10-10 03:13

from django.db import migrations


def populate_cost_types(apps, schema_editor):
    """
    Poblar la tabla de tipos de costo con los datos iniciales
    basados en Invoice.TIPO_COSTO_CHOICES
    """
    CostType = apps.get_model('catalogs', 'CostType')
    
    # Datos iniciales basados en TIPO_COSTO_CHOICES
    cost_types_data = [
        {
            'code': 'FLETE',
            'name': 'Flete',
            'description': 'Costo de transporte marítimo internacional',
            'category': 'maritimo',
            'display_order': 1,
            'is_active': True,
        },
        {
            'code': 'CARGOS_NAVIERA',
            'name': 'Cargos de Naviera',
            'description': 'Cargos adicionales de la naviera (ej: BAF, CAF, security)',
            'category': 'maritimo',
            'display_order': 2,
            'is_active': True,
        },
        {
            'code': 'TRANSPORTE',
            'name': 'Transporte',
            'description': 'Transporte terrestre por carretera',
            'category': 'terrestre',
            'display_order': 3,
            'is_active': True,
        },
        {
            'code': 'ADUANA',
            'name': 'Aduana',
            'description': 'Trámites y gastos aduanales',
            'category': 'aduanal',
            'display_order': 4,
            'is_active': True,
        },
        {
            'code': 'ALMACENAJE',
            'name': 'Almacenaje',
            'description': 'Costos de almacenamiento en puerto o bodega',
            'category': 'almacenaje',
            'display_order': 5,
            'is_active': True,
        },
        {
            'code': 'DEMORA',
            'name': 'Demora',
            'description': 'Cargos por demora o estadía de contenedores',
            'category': 'otro',
            'display_order': 6,
            'is_active': True,
        },
        {
            'code': 'OTRO',
            'name': 'Otro',
            'description': 'Otros costos no categorizados',
            'category': 'otro',
            'display_order': 7,
            'is_active': True,
        },
    ]
    
    # Crear los tipos de costo
    for cost_type_data in cost_types_data:
        CostType.objects.get_or_create(
            code=cost_type_data['code'],
            defaults=cost_type_data
        )


def reverse_populate_cost_types(apps, schema_editor):
    """
    Eliminar los tipos de costo creados (para reversión)
    """
    CostType = apps.get_model('catalogs', 'CostType')
    CostType.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0003_costtype'),
    ]

    operations = [
        migrations.RunPython(populate_cost_types, reverse_populate_cost_types),
    ]
