# Generated by Django 5.1.4 on 2025-10-10 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0004_populate_cost_types'),
    ]

    operations = [
        # 1. Crear el modelo CostCategory
        migrations.CreateModel(
            name='CostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(help_text='Código único de la categoría (ej: maritimo, terrestre)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Nombre descriptivo de la categoría', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Descripción detallada de la categoría', null=True)),
                ('color', models.CharField(default='#6B7280', help_text='Color en formato hexadecimal para visualización (ej: #3B82F6)', max_length=7)),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la categoría está activa')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Orden de visualización (menor número aparece primero)')),
            ],
            options={
                'verbose_name': 'Categoría de Costo',
                'verbose_name_plural': 'Categorías de Costo',
                'db_table': 'catalogs_cost_category',
                'ordering': ['display_order', 'name'],
            },
        ),
        # 2. Añadir índices a CostCategory
        migrations.AddIndex(
            model_name='costcategory',
            index=models.Index(fields=['code'], name='catalogs_co_code_bbd698_idx'),
        ),
        migrations.AddIndex(
            model_name='costcategory',
            index=models.Index(fields=['is_active'], name='catalogs_co_is_acti_baf55f_idx'),
        ),
        migrations.AddIndex(
            model_name='costcategory',
            index=models.Index(fields=['display_order'], name='catalogs_co_display_a98e76_idx'),
        ),
        # 3. Renombrar el campo category actual a category_old
        migrations.RenameField(
            model_name='costtype',
            old_name='category',
            new_name='category_old',
        ),
        # 4. Crear el nuevo campo category como ForeignKey
        migrations.AddField(
            model_name='costtype',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Categoría del tipo de costo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cost_types', to='catalogs.costcategory'),
        ),
    ]
