# Generated by Django 5.1.4 on 2025-10-10 03:41

from django.db import migrations


def populate_categories_and_migrate(apps, schema_editor):
    """
    1. Poblar las categorías de costo
    2. Migrar datos de category_old a category (ForeignKey)
    """
    CostCategory = apps.get_model('catalogs', 'CostCategory')
    CostType = apps.get_model('catalogs', 'CostType')
    
    # 1. Crear las categorías
    categories_data = [
        {
            'code': 'maritimo',
            'name': 'Marítimo',
            'description': 'Costos relacionados con transporte marítimo y servicios portuarios',
            'color': '#3B82F6',  # blue
            'display_order': 1,
        },
        {
            'code': 'terrestre',
            'name': 'Terrestre',
            'description': 'Costos de transporte por carretera y servicios terrestres',
            'color': '#8B5CF6',  # purple
            'display_order': 2,
        },
        {
            'code': 'aduanal',
            'name': 'Aduanal',
            'description': 'Trámites, impuestos y servicios aduanales',
            'color': '#F59E0B',  # orange
            'display_order': 3,
        },
        {
            'code': 'almacenaje',
            'name': 'Almacenaje',
            'description': 'Costos de almacenamiento y bodegaje',
            'color': '#EAB308',  # yellow
            'display_order': 4,
        },
        {
            'code': 'otro',
            'name': 'Otro',
            'description': 'Otros costos no categorizados',
            'color': '#6B7280',  # gray
            'display_order': 5,
        },
    ]
    
    category_map = {}
    for cat_data in categories_data:
        category, created = CostCategory.objects.get_or_create(
            code=cat_data['code'],
            defaults=cat_data
        )
        category_map[cat_data['code']] = category
    
    # 2. Migrar los tipos de costo existentes
    cost_type_category_mapping = {
        'FLETE': 'maritimo',
        'CARGOS_NAVIERA': 'maritimo',
        'TRANSPORTE': 'terrestre',
        'ADUANA': 'aduanal',
        'ALMACENAJE': 'almacenaje',
        'DEMORA': 'otro',
        'OTRO': 'otro',
    }
    
    for cost_type in CostType.objects.all():
        category_code = cost_type_category_mapping.get(cost_type.code, 'otro')
        cost_type.category = category_map[category_code]
        cost_type.save()


def reverse_migrate(apps, schema_editor):
    """
    Revertir: eliminar categorías y limpiar el campo category
    """
    CostCategory = apps.get_model('catalogs', 'CostCategory')
    CostType = apps.get_model('catalogs', 'CostType')
    
    # Limpiar la referencia de ForeignKey
    for cost_type in CostType.objects.all():
        cost_type.category = None
        cost_type.save()
    
    # Eliminar las categorías
    CostCategory.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0005_step1_create_category_model_and_rename_field'),
    ]

    operations = [
        migrations.RunPython(populate_categories_and_migrate, reverse_migrate),
    ]
