# Generated by Django 5.1.4 on 2025-10-14 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0007_remove_category_old_field'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER INDEX IF EXISTS catalogs_co_categor_285528_idx RENAME TO catalogs_co_categor_7fab5a_idx;",
            reverse_sql="ALTER INDEX IF EXISTS catalogs_co_categor_7fab5a_idx RENAME TO catalogs_co_categor_285528_idx;",
        ),
    ]
