# Generated by Django 5.1.4 on 2025-10-14 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0007_remove_category_old_field'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='costtype',
            new_name='catalogs_co_categor_7fab5a_idx',
            old_name='catalogs_co_categor_285528_idx',
        ),
    ]
