# Generated by Django 5.1.4 on 2025-10-11 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0007_remove_category_old_field'),
    ]

    operations = [
    ]
