# Generated by Django 5.1.4 on 2025-10-17 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0008_rename_catalogs_co_categor_285528_idx_catalogs_co_categor_7fab5a_idx'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1
                    FROM pg_indexes
                    WHERE schemaname = 'public'
                      AND indexname = 'catalogs_co_categor_285528_idx'
                ) THEN
                    EXECUTE 'ALTER INDEX "catalogs_co_categor_285528_idx" RENAME TO "catalogs_co_categor_7fab5a_idx"';
                END IF;
            END;
            $$;
            """,
            reverse_sql="""
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1
                    FROM pg_indexes
                    WHERE schemaname = 'public'
                      AND indexname = 'catalogs_co_categor_7fab5a_idx'
                ) THEN
                    EXECUTE 'ALTER INDEX "catalogs_co_categor_7fab5a_idx" RENAME TO "catalogs_co_categor_285528_idx"';
                END IF;
            END;
            $$;
            """,
        ),
        migrations.AlterField(
            model_name='provider',
            name='tipo',
            field=models.CharField(choices=[('naviera', 'Naviera'), ('agente_local', 'Agente Local'), ('agencia_aduanal', 'Agencia Aduanal'), ('agente_origen', 'Agente de Origen'), ('aseguradora', 'Aseguradora'), ('aerolinea', 'Aerolínea'), ('consolidadora', 'Consolidadora'), ('almacenadora', 'Almacenadora'), ('transportista', 'Transportista'), ('otro', 'Otro')], default='otro', help_text='Tipo de proveedor', max_length=20),
        ),
    ]
