# Generated by Django 5.1.4 on 2025-10-18 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0009_rename_catalogs_co_categor_285528_idx_catalogs_co_categor_7fab5a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='costtype',
            name='is_linked_to_ot',
            field=models.BooleanField(default=False, help_text='Indica si este tipo de costo debe enlazarse/sincronizarse con la OT (ej: Flete, Cargos de Naviera)'),
        ),
    ]
