# Generated by Django 5.1.4 on 2025-10-18 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0010_add_is_linked_to_ot_to_cost_type'),
    ]

    operations = [
        # No operations needed - just a placeholder migration
    ]
