# Generated by Django 5.1.4 on 2025-10-18 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0011_fix_unique_constraint_for_soft_delete'),
    ]

    operations = [
        # No operations needed - just a placeholder migration
    ]
