# Generated by Django 5.1.4 on 2025-10-19 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0012_fix_unique_constraint_creditnote'),
    ]

    operations = [
    ]
