# Generated by Django 5.1.4 on 2025-10-19 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0012_fix_unique_constraint_creditnote'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='costtype',
            new_name='catalogs_co_categor_7fab5a_idx',
            old_name='catalogs_co_categor_285528_idx',
        ),
    ]
