# Generated by Django 5.1.4 on 2025-11-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0014_mark_linked_cost_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoicePatternCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(help_text='Nombre descriptivo del patrón (ej: DTE El Salvador, CCF, etc)', max_length=100, unique=True)),
                ('tipo_factura', models.CharField(choices=[('nacional', 'Factura Nacional'), ('internacional', 'Factura Internacional')], db_index=True, default='nacional', help_text='Tipo de factura (nacional o internacional)', max_length=20)),
                ('activo', models.BooleanField(db_index=True, default=True, help_text='Si está activo, se usará en la extracción automática')),
                ('prioridad', models.IntegerField(default=10, help_text='Orden de aplicación (menor = mayor prioridad)')),
                ('patron_numero_factura', models.TextField(blank=True, help_text='Regex para extraer número de factura. Ej: DTE-\\d{2}-[A-Z]\\d+-\\d+')),
                ('patron_numero_control', models.TextField(blank=True, help_text='Regex para extraer número de control (El Salvador DTE)')),
                ('patron_fecha_emision', models.TextField(blank=True, help_text='Regex para extraer fecha de emisión')),
                ('patron_nit_emisor', models.TextField(blank=True, help_text='Regex para extraer NIT del emisor')),
                ('patron_nombre_emisor', models.TextField(blank=True, help_text='Regex para extraer nombre del emisor')),
                ('patron_nit_cliente', models.TextField(blank=True, help_text='Regex para extraer NIT del cliente')),
                ('patron_nombre_cliente', models.TextField(blank=True, help_text='Regex para extraer nombre del cliente')),
                ('patron_subtotal', models.TextField(blank=True, help_text='Regex para extraer subtotal')),
                ('patron_iva', models.TextField(blank=True, help_text='Regex para extraer IVA')),
                ('patron_total', models.TextField(blank=True, help_text='Regex para extraer monto total')),
                ('patron_retencion', models.TextField(blank=True, help_text='Regex para extraer monto de retención (si aplica)')),
                ('porcentaje_iva_default', models.DecimalField(decimal_places=2, default=13.0, help_text='Porcentaje de IVA por defecto (13% en El Salvador)', max_digits=5)),
                ('permite_iva_mixto', models.BooleanField(default=True, help_text='Si permite líneas con y sin IVA en la misma factura')),
                ('notas', models.TextField(blank=True, help_text='Notas sobre el uso del patrón')),
                ('ejemplo_texto', models.TextField(blank=True, help_text='Ejemplo de texto de factura que matchea con este patrón')),
            ],
            options={
                'verbose_name': 'Patrón de Factura',
                'verbose_name_plural': 'Patrones de Facturas',
                'db_table': 'catalogs_invoice_pattern',
                'ordering': ['prioridad', 'nombre'],
            },
        ),
        migrations.AddIndex(
            model_name='invoicepatterncatalog',
            index=models.Index(fields=['activo', 'prioridad'], name='catalogs_in_activo_7f2908_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicepatterncatalog',
            index=models.Index(fields=['tipo_factura', 'activo'], name='catalogs_in_tipo_fa_5f78f1_idx'),
        ),
    ]
