# Generated by Django 5.1.4 on 2025-11-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0015_add_invoice_pattern_catalog'),
    ]

    operations = [
        # migrations.RenameIndex(  # ← COMENTADO: Índice no existe
        #     model_name='costtype',
        #     new_name='catalogs_co_categor_7fab5a_idx',
        #     old_name='catalogs_co_categor_285528_idx',
        # ),
        migrations.AddField(
            model_name='invoicepatterncatalog',
            name='patron_retencion_iva',
            field=models.TextField(blank=True, help_text='Regex para extraer retención de IVA (1% para Grandes Contribuyentes)'),
        ),
        migrations.AddField(
            model_name='invoicepatterncatalog',
            name='patron_retencion_renta',
            field=models.TextField(blank=True, help_text='Regex para extraer retención de renta'),
        ),
        migrations.AddField(
            model_name='invoicepatterncatalog',
            name='patron_subtotal_exento',
            field=models.TextField(blank=True, help_text='Regex para extraer subtotal exento (sin IVA)'),
        ),
        migrations.AddField(
            model_name='invoicepatterncatalog',
            name='patron_subtotal_gravado',
            field=models.TextField(blank=True, help_text='Regex para extraer subtotal gravado (base imponible con IVA)'),
        ),
        migrations.AlterField(
            model_name='invoicepatterncatalog',
            name='patron_retencion',
            field=models.TextField(blank=True, help_text='Regex para extraer monto de retención general'),
        ),
        migrations.AlterField(
            model_name='invoicepatterncatalog',
            name='patron_subtotal',
            field=models.TextField(blank=True, help_text='Regex para extraer subtotal (total antes de IVA)'),
        ),
        migrations.AlterField(
            model_name='invoicepatterncatalog',
            name='patron_total',
            field=models.TextField(blank=True, help_text='Regex para extraer monto total final'),
        ),
    ]
