# Generated by Django 5.1.4 on 2025-11-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0016_add_detailed_pattern_fields'),
    ]

    operations = [
        # migrations.RenameIndex(
        #     model_name='costtype',
        #     new_name='catalogs_co_categor_7fab5a_idx',
        #     old_name='catalogs_co_categor_285528_idx',
        # ),
        migrations.AddField(
            model_name='invoicepatterncatalog',
            name='patron_otros_montos',
            field=models.TextField(blank=True, help_text='Regex para extraer otros montos no afectos (cargos adicionales que no llevan IVA)'),
        ),
    ]
