# Generated by Django 5.1.4 on 2025-11-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0017_add_otros_montos_field'),
    ]

    operations = [
        # migrations.RenameIndex(
        #     model_name='costtype',
        #     new_name='catalogs_co_categor_7fab5a_idx',
        #     old_name='catalogs_co_categor_285528_idx',
        # ),
        migrations.AddField(
            model_name='invoicepatterncatalog',
            name='tipo_patron',
            field=models.CharField(choices=[('costo', 'Factura de Costo (Proveedores)'), ('venta', 'Factura de Venta (Clientes)')], db_index=True, default='costo', help_text='¿Es patrón para facturas de COSTO (proveedores) o de VENTA (clientes)?', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoicepatterncatalog',
            name='tipo_factura',
            field=models.CharField(choices=[('nacional', 'Factura Nacional'), ('internacional', 'Factura Internacional')], db_index=True, default='nacional', help_text='Tipo de factura (nacional o internacional). Solo aplica para patrones de VENTA', max_length=20),
        ),
    ]
