# Generated by Django 5.1.4 on 2025-11-01 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0018_add_tipo_patron_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoicepatterncatalog',
            options={'ordering': ['tipo_patron', '-es_grupo_principal', 'prioridad', 'nombre'], 'verbose_name': 'Patrón de Factura', 'verbose_name_plural': 'Patrones de Facturas'},
        ),
        # migrations.RenameIndex(
        #     model_name='costtype',
        #     new_name='catalogs_co_categor_7fab5a_idx',
        #     old_name='catalogs_co_categor_285528_idx',
        # ),
        migrations.AddField(
            model_name='invoicepatterncatalog',
            name='campo_objetivo',
            field=models.CharField(blank=True, db_index=True, help_text='Campo específico a extraer: numero_factura, mbl, hbl, total, fecha, iva, etc.', max_length=100),
        ),
        migrations.AddField(
            model_name='invoicepatterncatalog',
            name='case_sensitive',
            field=models.BooleanField(default=False, help_text='Si el patrón regex distingue mayúsculas/minúsculas'),
        ),
        migrations.AddField(
            model_name='invoicepatterncatalog',
            name='casos_prueba',
            field=models.JSONField(blank=True, default=list, help_text="Casos de prueba: [{'input': 'texto', 'expected': 'valor', 'description': '...'}]"),
        ),
        migrations.AddField(
            model_name='invoicepatterncatalog',
            name='es_grupo_principal',
            field=models.BooleanField(db_index=True, default=True, help_text='True = es un grupo contenedor. False = es un patrón individual dentro de un grupo'),
        ),
        migrations.AddField(
            model_name='invoicepatterncatalog',
            name='exito_count',
            field=models.IntegerField(default=0, help_text='Número de extracciones exitosas con este patrón'),
        ),
        migrations.AddField(
            model_name='invoicepatterncatalog',
            name='grupo_padre',
            field=models.ForeignKey(blank=True, help_text='Grupo al que pertenece este patrón (solo para patrones individuales)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patrones_hijos', to='catalogs.invoicepatterncatalog'),
        ),
        migrations.AddField(
            model_name='invoicepatterncatalog',
            name='patron_regex',
            field=models.TextField(blank=True, help_text='Regex específico cuando es patrón individual (alternativa a los patron_* específicos)'),
        ),
        migrations.AddField(
            model_name='invoicepatterncatalog',
            name='proveedor',
            field=models.ForeignKey(blank=True, help_text='Para patrones de COSTO, proveedor asociado. Permite agrupar patrones por proveedor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patrones_factura', to='catalogs.provider'),
        ),
        migrations.AddField(
            model_name='invoicepatterncatalog',
            name='tipo_documento',
            field=models.CharField(blank=True, db_index=True, help_text='Para patrones de VENTA: DTE, CCF, Invoice, etc. Permite agrupar patrones por tipo', max_length=50),
        ),
        migrations.AddField(
            model_name='invoicepatterncatalog',
            name='ultima_uso',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora del último uso de este patrón', null=True),
        ),
        migrations.AddField(
            model_name='invoicepatterncatalog',
            name='uso_count',
            field=models.IntegerField(default=0, help_text='Número de veces que se ha usado este patrón en extracciones'),
        ),
        migrations.AddIndex(
            model_name='invoicepatterncatalog',
            index=models.Index(fields=['tipo_patron', 'activo'], name='catalogs_in_tipo_pa_3ba0fb_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicepatterncatalog',
            index=models.Index(fields=['es_grupo_principal', 'activo'], name='catalogs_in_es_grup_0d21a5_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicepatterncatalog',
            index=models.Index(fields=['proveedor', 'activo'], name='catalogs_in_proveed_c0e436_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicepatterncatalog',
            index=models.Index(fields=['campo_objetivo'], name='catalogs_in_campo_o_d3023a_idx'),
        ),
    ]
