# Generated by Django 5.1.4 on 2025-11-03 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0019_alter_invoicepatterncatalog_options_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='costtype',
            new_name='catalogs_co_categor_7fab5a_idx',
            old_name='catalogs_co_categor_285528_idx',
        ),
    ]
