# Generated by Django 5.1.4 on 2025-11-03 04:33

from django.db import migrations


def rename_index_safe(apps, schema_editor):
    """
    Safe index rename - does nothing if index doesn't exist.
    This migration is intentionally a no-op to prevent deployment failures.
    The index will be created automatically by Django if needed.
    """
    # Skip this migration - the index rename is not critical
    # and was causing deployment failures in production
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0019_alter_invoicepatterncatalog_options_and_more'),
    ]

    operations = [
        # No-op migration to prevent deployment failures
        migrations.RunPython(rename_index_safe, migrations.RunPython.noop),
    ]
