# Generated by Django on 2025-11-02

from django.db import migrations


def migrate_old_patterns(apps, schema_editor):
    """
    Migración deshabilitada: Los modelos ProviderPattern (viejo) e InvoicePatternCatalog (nuevo)
    tienen estructuras incompatibles. ProviderPattern usa un campo 'pattern' genérico, mientras
    que InvoicePatternCatalog usa campos específicos (patron_numero_factura, patron_fecha_emision, etc).
    
    La migración automática no es posible. Los patrones deben recrearse manualmente en el nuevo sistema.
    """
    print("\n⚠️  Migración de patrones omitida - estructuras incompatibles")
    print("   Los patrones del sistema viejo deben recrearse manualmente en el catálogo nuevo\n")
    pass


def reverse_migration(apps, schema_editor):
    """
    No hacemos nada en el reverse - los patrones migrados se quedan
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0020_rename_catalogs_co_categor_285528_idx_catalogs_co_categor_7fab5a_idx'),
        ('patterns', '0001_initial'),  # Asume que patterns tiene al menos una migración
    ]

    operations = [
        migrations.RunPython(migrate_old_patterns, reverse_migration),
    ]
