# Generated by Django on 2025-11-02

from django.db import migrations


def migrate_old_patterns(apps, schema_editor):
    """
    Migra patrones del sistema viejo (patterns.ProviderPattern) 
    al nuevo sistema (catalogs.InvoicePatternCatalog).
    """
    InvoicePatternCatalog = apps.get_model('catalogs', 'InvoicePatternCatalog')
    
    # Intentar obtener el modelo viejo, si existe
    try:
        ProviderPattern = apps.get_model('patterns', 'ProviderPattern')
    except LookupError:
        # Si no existe el modelo viejo, no hay nada que migrar
        print("⚠️  Modelo patterns.ProviderPattern no encontrado - omitiendo migración")
        return
    
    # Mapeo de campos
    tipo_patron_map = {
        'numero_factura': 'numero_factura',
        'invoice_number': 'numero_factura',
        'fecha_emision': 'fecha_emision',
        'emission_date': 'fecha_emision',
        'fecha_vencimiento': 'fecha_vencimiento',
        'due_date': 'fecha_vencimiento',
        'monto_total': 'monto_total',
        'total_amount': 'monto_total',
        'subtotal': 'subtotal',
        'mbl': 'mbl',
        'hbl': 'hbl',
        'numero_contenedor': 'numero_contenedor',
        'container_number': 'numero_contenedor',
    }
    
    # Obtener patrones viejos activos
    old_patterns = ProviderPattern.objects.filter(is_active=True).select_related('provider', 'target_field')
    
    migrated = 0
    skipped = 0
    
    print(f"\n📊 Encontrados {old_patterns.count()} patrones activos en el sistema viejo")
    
    for old_pattern in old_patterns:
        try:
            # Mapear nombre de proveedor
            proveedor_nombre = old_pattern.provider.name if old_pattern.provider else 'GENERICO'
            
            # Mapear tipo de patrón
            target_field_name = old_pattern.target_field.field_name if old_pattern.target_field else 'numero_factura'
            tipo_patron = tipo_patron_map.get(target_field_name, 'numero_factura')
            
            # Verificar si ya existe
            existing = InvoicePatternCatalog.objects.filter(
                proveedor=proveedor_nombre,
                tipo_patron=tipo_patron,
                patron=old_pattern.pattern,
            ).exists()
            
            if existing:
                print(f'⚠️  Patrón duplicado: {proveedor_nombre} - {tipo_patron}')
                skipped += 1
                continue
            
            # Crear el nuevo patrón
            InvoicePatternCatalog.objects.create(
                proveedor=proveedor_nombre,
                categoria='PROVEEDOR',
                tipo_patron=tipo_patron,
                patron=old_pattern.pattern,
                es_regex=True,
                prioridad=old_pattern.priority,
                descripcion=old_pattern.description or f'Migrado desde patrón ID {old_pattern.id}',
                ejemplo_texto=old_pattern.example_text or '',
                activo=old_pattern.is_active,
            )
            
            print(f'✓ Migrado: {proveedor_nombre} - {tipo_patron}')
            migrated += 1
            
        except Exception as e:
            print(f'❌ Error migrando patrón ID {old_pattern.id}: {str(e)}')
    
    print(f"\n✓ Patrones migrados: {migrated}")
    print(f"⚠️  Patrones omitidos: {skipped}\n")


def reverse_migration(apps, schema_editor):
    """
    No hacemos nada en el reverse - los patrones migrados se quedan
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0020_rename_catalogs_co_categor_285528_idx_catalogs_co_categor_7fab5a_idx'),
        ('patterns', '0001_initial'),  # Asume que patterns tiene al menos una migración
    ]

    operations = [
        migrations.RunPython(migrate_old_patterns, reverse_migration),
    ]
