# Generated by Django 5.1.4 on 2025-11-03 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0021_migrate_old_patterns_to_catalog'),
    ]

    operations = [
        # No-op migration: El índice ya existe en producción con nombre diferente
        # Django quiere renombrarlo pero esto causa problemas en Railway
        migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop),
    ]
