# Generated by Django 5.1.4 on 2025-11-03 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0022_rename_catalogs_co_categor_285528_idx_catalogs_co_categor_7fab5a_idx'),
    ]

    operations = [
        # No-op migration: El índice ya existe en producción con nombre diferente
        # Django quiere renombrarlo pero esto causa problemas en Railway
        migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop),
    ]
