# Generated by Django 5.1.4 on 2025-11-03 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0022_rename_catalogs_co_categor_285528_idx_catalogs_co_categor_7fab5a_idx'),
        ('catalogs', '0023_rename_catalogs_co_categor_285528_idx_catalogs_co_categor_7fab5a_idx'),
    ]

    operations = [
        # Merge migration - no operations needed
    ]
