# Generated by Django 5.1.4 on 2025-11-03 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0024_merge_migrations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicepatterncatalog',
            name='nombre',
            field=models.CharField(help_text='Nombre descriptivo del patrón (ej: DTE El Salvador, CCF, etc)', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='invoicepatterncatalog',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('nombre',), name='unique_active_pattern_name'),
        ),
    ]
