# Generated by Django 5.1.4 on 2025-10-04 23:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAutoProcessingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Si está activo el procesamiento automático de emails')),
                ('check_interval_minutes', models.IntegerField(default=15, help_text='Intervalo en minutos para revisar nuevos emails')),
                ('target_folders', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text="Lista de carpetas a monitorear (ej: ['Inbox', 'Inbox/DTEs'])", size=None)),
                ('subject_filters', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text="Filtros de asunto para buscar (ej: ['DTE', 'Factura', 'Invoice'])", size=None)),
                ('sender_whitelist', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, default=list, help_text='Lista de emails permitidos (vacío = todos permitidos)', size=None)),
                ('auto_parse_enabled', models.BooleanField(default=True, help_text='Si se debe usar auto_parse al crear facturas')),
                ('max_emails_per_run', models.IntegerField(default=50, help_text='Máximo de emails a procesar en cada ejecución')),
                ('last_run_at', models.DateTimeField(blank=True, help_text='Fecha y hora de la última ejecución', null=True)),
                ('last_run_status', models.CharField(blank=True, help_text='Estado de la última ejecución', max_length=500)),
            ],
            options={
                'verbose_name': 'Configuración de Email Automation',
                'verbose_name_plural': 'Configuraciones de Email Automation',
                'db_table': 'automation_email_config',
            },
        ),
        migrations.CreateModel(
            name='EmailProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message_id', models.CharField(db_index=True, help_text='Message-ID único del email (usado para deduplicación)', max_length=500, unique=True)),
                ('subject', models.CharField(help_text='Asunto del email', max_length=1000)),
                ('sender_email', models.EmailField(help_text='Email del remitente', max_length=254)),
                ('received_date', models.DateTimeField(help_text='Fecha y hora en que se recibió el email')),
                ('attachment_count', models.IntegerField(default=0, help_text='Cantidad de archivos adjuntos en el email')),
                ('attachment_filenames', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, default=list, help_text='Lista de nombres de archivos adjuntos', size=None)),
                ('status', models.CharField(choices=[('success', 'Exitoso'), ('failed', 'Fallido'), ('partial', 'Parcial'), ('skipped', 'Omitido')], default='success', help_text='Estado del procesamiento', max_length=20)),
                ('invoices_count', models.IntegerField(default=0, help_text='Cantidad de facturas creadas exitosamente')),
                ('error_message', models.TextField(blank=True, help_text='Mensaje de error si el procesamiento falló')),
                ('processing_time_seconds', models.FloatField(blank=True, help_text='Tiempo de procesamiento en segundos', null=True)),
                ('folder_path', models.CharField(default='Inbox', help_text='Ruta de la carpeta donde se encontró el email (ej: Inbox, Inbox/DTEs)', max_length=500)),
                ('auto_matched_ots', models.IntegerField(default=0, help_text='Cantidad de facturas que se asignaron automáticamente a OTs')),
                ('invoices_created', models.ManyToManyField(blank=True, help_text='Facturas creadas a partir de este email', related_name='email_logs', to='invoices.invoice')),
            ],
            options={
                'db_table': 'automation_email_processing_log',
                'ordering': ['-received_date'],
                'indexes': [models.Index(fields=['message_id'], name='automation__message_403db5_idx'), models.Index(fields=['-received_date'], name='automation__receive_07b2f4_idx'), models.Index(fields=['status'], name='automation__status_12a3be_idx'), models.Index(fields=['sender_email'], name='automation__sender__d3503d_idx')],
            },
        ),
    ]
