# Generated by Django 5.1.4 on 2025-10-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegexPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='Nombre identificador del patrón', max_length=100, unique=True)),
                ('description', models.TextField(help_text='Descripción de qué busca o valida este patrón')),
                ('pattern', models.TextField(help_text='Expresión regular (regex)')),
                ('category', models.CharField(choices=[('container', 'Número de Contenedor'), ('bl', 'Bill of Lading (BL/MBL/HBL)'), ('ot', 'Orden de Trabajo (OT)'), ('date', 'Fecha'), ('nit', 'NIT'), ('email', 'Email'), ('phone', 'Teléfono'), ('other', 'Otro')], default='other', help_text='Categoría del patrón', max_length=20)),
                ('test_cases', models.JSONField(blank=True, default=list, help_text='Casos de prueba para validar el patrón')),
                ('usage_stats', models.JSONField(blank=True, default=dict, help_text='Estadísticas de uso del patrón')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el patrón está activo')),
                ('priority', models.IntegerField(default=0, help_text='Prioridad del patrón (mayor = más prioritario)')),
            ],
            options={
                'verbose_name': 'Patrón de Regex',
                'verbose_name_plural': 'Patrones de Regex',
                'db_table': 'patterns_regexpattern',
                'ordering': ['-priority', 'category', 'name'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='patterns_re_categor_da9c60_idx'), models.Index(fields=['priority', 'is_active'], name='patterns_re_priorit_07d9dd_idx')],
            },
        ),
    ]
