# Generated by Django 5.1.4 on 2025-10-08 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0002_provider_dias_credito_provider_notas_credito_and_more'),
        ('patterns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text="Nombre identificador del patrón (ej: 'MSC - Factura Header')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Descripción de qué busca este patrón')),
                ('pattern', models.TextField(help_text='Expresión regular para identificar al proveedor')),
                ('pattern_type', models.CharField(choices=[('name', 'Nombre del Proveedor'), ('nit', 'NIT'), ('header', 'Encabezado de Factura'), ('footer', 'Pie de Factura'), ('format', 'Formato General'), ('other', 'Otro')], default='name', help_text='Tipo de patrón', max_length=20)),
                ('test_cases', models.JSONField(blank=True, default=list, help_text="Casos de prueba: [{'input': 'texto', 'expected': true/false, 'description': '...'}]")),
                ('usage_count', models.IntegerField(default=0, help_text='Número de veces que se ha usado este patrón')),
                ('success_count', models.IntegerField(default=0, help_text='Número de coincidencias exitosas')),
                ('last_used', models.DateTimeField(blank=True, help_text='Última vez que se usó este patrón', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el patrón está activo')),
                ('priority', models.IntegerField(default=0, help_text='Prioridad del patrón (mayor = más prioritario)')),
                ('case_sensitive', models.BooleanField(default=False, help_text='Si el patrón distingue mayúsculas/minúsculas')),
                ('provider', models.ForeignKey(help_text='Proveedor al que pertenece este patrón', on_delete=django.db.models.deletion.CASCADE, related_name='regex_patterns', to='catalogs.provider')),
            ],
            options={
                'verbose_name': 'Patrón de Proveedor',
                'verbose_name_plural': 'Patrones de Proveedores',
                'db_table': 'patterns_provider_pattern',
                'ordering': ['-priority', 'provider__nombre', 'name'],
                'indexes': [models.Index(fields=['provider', 'is_active'], name='patterns_pr_provide_9fc9cb_idx'), models.Index(fields=['pattern_type', 'is_active'], name='patterns_pr_pattern_21ee1b_idx'), models.Index(fields=['priority'], name='patterns_pr_priorit_7112d5_idx')],
                'unique_together': {('provider', 'name')},
            },
        ),
    ]
