# Generated by Django 5.1.4 on 2025-10-08 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0002_providerpattern'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(help_text="Código único del campo (ej: 'invoice_number', 'mbl', 'total_amount')", max_length=50, unique=True)),
                ('name', models.CharField(help_text="Nombre descriptivo del campo (ej: 'Número de Factura', 'MBL')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Descripción detallada del campo y su uso')),
                ('data_type', models.CharField(choices=[('text', 'Texto'), ('number', 'Número'), ('decimal', 'Decimal'), ('date', 'Fecha'), ('boolean', 'Booleano')], default='text', help_text='Tipo de dato esperado para este campo', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el campo está activo y disponible')),
                ('priority', models.IntegerField(default=0, help_text='Prioridad del campo (mayor = más importante)')),
                ('example_value', models.CharField(blank=True, help_text='Ejemplo de valor para este campo', max_length=255)),
            ],
            options={
                'verbose_name': 'Campo Objetivo',
                'verbose_name_plural': 'Campos Objetivo',
                'db_table': 'patterns_target_field',
                'ordering': ['-priority', 'name'],
                'indexes': [models.Index(fields=['is_active', 'priority'], name='patterns_ta_is_acti_69af53_idx'), models.Index(fields=['code'], name='patterns_ta_code_9f3394_idx')],
            },
        ),
    ]
