# Generated by Django 5.1.4 on 2025-10-08 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0002_provider_dias_credito_provider_notas_credito_and_more'),
        ('patterns', '0003_targetfield'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='providerpattern',
            name='patterns_pr_pattern_21ee1b_idx',
        ),
        migrations.RemoveField(
            model_name='providerpattern',
            name='pattern_type',
        ),
        migrations.AddField(
            model_name='providerpattern',
            name='target_field',
            field=models.ForeignKey(blank=True, help_text='Campo objetivo que este patrón extrae', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_patterns', to='patterns.targetfield'),
        ),
        migrations.AlterField(
            model_name='providerpattern',
            name='name',
            field=models.CharField(help_text="Nombre identificador del patrón (ej: 'MSC - Número de Factura')", max_length=100),
        ),
        migrations.AlterField(
            model_name='providerpattern',
            name='pattern',
            field=models.TextField(help_text='Expresión regular para extraer el campo'),
        ),
        migrations.AddIndex(
            model_name='providerpattern',
            index=models.Index(fields=['target_field', 'is_active'], name='patterns_pr_target__30479a_idx'),
        ),
    ]
