# Generated by Django 5.1.4 on 2025-10-23 10:00

from django.db import migrations

def create_generic_target_fields(apps, schema_editor):
    TargetField = apps.get_model('patterns', 'TargetField')
    TargetField.objects.get_or_create(
        code='numero_control',
        defaults={
            'name': 'Número de Control',
            'description': 'Número de control de la factura',
            'data_type': 'text',
        }
    )
    TargetField.objects.get_or_create(
        code='fecha_emision',
        defaults={
            'name': 'Fecha de Emisión',
            'description': 'Fecha de emisión de la factura',
            'data_type': 'date',
        }
    )
    TargetField.objects.get_or_create(
        code='monto_total',
        defaults={
            'name': 'Monto Total',
            'description': 'Monto total de la factura, incluyendo IVA',
            'data_type': 'decimal',
        }
    )

class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0004_remove_providerpattern_patterns_pr_pattern_21ee1b_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(create_generic_target_fields),
    ]
