# Generated by Django 5.1.4 on 2025-10-23 10:00

from django.db import migrations

def create_numero_control_target_field(apps, schema_editor):
    TargetField = apps.get_model('patterns', 'TargetField')
    TargetField.objects.get_or_create(
        code='numero_control',
        defaults={
            'name': 'Número de Control',
            'description': 'Número de control de la factura',
            'data_type': 'text',
        }
    )

class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0005_add_generic_target_fields'),
    ]

    operations = [
        migrations.RunPython(create_numero_control_target_field),
    ]
