# Generated by Django 5.1.4 on 2025-10-25 03:39

import common.storage_backends
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_aliases', '0007_rename_client_reso_origina_idx_client_reso_origina_a096a1_idx_and_more'),
        ('invoices', '0019_update_tipo_costo_dynamic'),
        ('ots', '0012_ot_estado_facturacion_venta_ot_margen_bruto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('numero_factura', models.CharField(db_index=True, help_text='Número de factura de venta del sistema externo', max_length=50, unique=True)),
                ('fecha_emision', models.DateField(help_text='Fecha de emisión de la factura')),
                ('fecha_vencimiento', models.DateField(help_text='Fecha de vencimiento del pago')),
                ('monto_total', models.DecimalField(decimal_places=2, help_text='Monto total de la factura de venta', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto total pagado (suma de pagos validados)', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('monto_pendiente', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto pendiente de pago (calculado automáticamente)', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, help_text='Subtotal sin IVA', max_digits=15, null=True)),
                ('iva', models.DecimalField(blank=True, decimal_places=2, help_text='Monto de IVA', max_digits=15, null=True)),
                ('descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Descuento aplicado', max_digits=15)),
                ('archivo_pdf', models.FileField(blank=True, help_text='PDF de la factura de venta del sistema externo', null=True, storage=common.storage_backends.CloudinaryMediaStorage(), upload_to='sales_invoices/')),
                ('archivo_xml', models.FileField(blank=True, help_text='XML de factura electrónica (si aplica)', null=True, storage=common.storage_backends.CloudinaryMediaStorage(), upload_to='sales_invoices/xml/')),
                ('estado_facturacion', models.CharField(choices=[('borrador', 'Borrador'), ('emitida', 'Emitida'), ('enviada', 'Enviada al Cliente'), ('pagada', 'Pagada'), ('vencida', 'Vencida'), ('anulada', 'Anulada')], db_index=True, default='emitida', help_text='Estado de facturación', max_length=20)),
                ('estado_pago', models.CharField(choices=[('pendiente', 'Pendiente de Pago'), ('pagado_parcial', 'Pagado Parcialmente'), ('pagado_total', 'Pagado Totalmente')], db_index=True, default='pendiente', help_text='Estado de pago', max_length=20)),
                ('autorizacion_sri', models.CharField(blank=True, help_text='Número de autorización SRI (si es electrónica)', max_length=100)),
                ('clave_acceso', models.CharField(blank=True, help_text='Clave de acceso de factura electrónica', max_length=100)),
                ('notas', models.TextField(blank=True, help_text='Observaciones o notas adicionales')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de los servicios facturados')),
                ('cliente', models.ForeignKey(help_text='Cliente al que se factura', on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='client_aliases.clientalias')),
                ('created_by', models.ForeignKey(help_text='Usuario que cargó la factura', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sales_invoices', to=settings.AUTH_USER_MODEL)),
                ('ot', models.ForeignKey(blank=True, help_text='Orden de trabajo asociada', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='ots.ot')),
                ('updated_by', models.ForeignKey(help_text='Último usuario que actualizó', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_sales_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Factura de Venta',
                'verbose_name_plural': 'Facturas de Venta',
                'db_table': 'sales_invoices',
                'ordering': ['-fecha_emision', '-numero_factura'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('fecha_pago', models.DateField(help_text='Fecha en que se realizó el pago')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto del pago', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('metodo_pago', models.CharField(choices=[('transferencia', 'Transferencia Bancaria'), ('cheque', 'Cheque'), ('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta de Crédito/Débito'), ('compensacion', 'Compensación'), ('nota_credito', 'Nota de Crédito'), ('otro', 'Otro')], help_text='Método de pago utilizado', max_length=20)),
                ('referencia', models.CharField(help_text='Número de referencia o transacción', max_length=100)),
                ('banco', models.CharField(blank=True, help_text='Banco de origen (si aplica)', max_length=100)),
                ('archivo_comprobante', models.FileField(blank=True, help_text='Comprobante de pago (PDF, imagen)', null=True, storage=common.storage_backends.CloudinaryMediaStorage(), upload_to='payment_receipts/')),
                ('estado', models.CharField(choices=[('pendiente_validacion', 'Pendiente de Validación'), ('validado', 'Validado'), ('rechazado', 'Rechazado')], db_index=True, default='pendiente_validacion', help_text='Estado de validación del pago', max_length=25)),
                ('fecha_validacion', models.DateTimeField(blank=True, help_text='Fecha y hora de validación', null=True)),
                ('notas', models.TextField(blank=True, help_text='Observaciones sobre el pago')),
                ('notas_rechazo', models.TextField(blank=True, help_text='Motivo del rechazo (si aplica)')),
                ('registrado_por', models.ForeignKey(help_text='Usuario que registró el pago', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_payments', to=settings.AUTH_USER_MODEL)),
                ('validado_por', models.ForeignKey(blank=True, help_text='Usuario (finanzas) que validó el pago', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_payments', to=settings.AUTH_USER_MODEL)),
                ('sales_invoice', models.ForeignKey(help_text='Factura de venta asociada', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.salesinvoice')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'payments',
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceSalesMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monto_asignado', models.DecimalField(decimal_places=2, help_text='Monto del costo asignado a esta venta (puede ser parcial)', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('porcentaje_markup', models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de markup aplicado sobre este costo', max_digits=6, null=True)),
                ('notas', models.TextField(blank=True, help_text='Notas sobre esta asociación')),
                ('cost_invoice', models.ForeignKey(help_text='Factura de costo asociada', on_delete=django.db.models.deletion.PROTECT, related_name='sales_mappings', to='invoices.invoice')),
                ('sales_invoice', models.ForeignKey(help_text='Factura de venta', on_delete=django.db.models.deletion.CASCADE, related_name='cost_mappings', to='sales.salesinvoice')),
            ],
            options={
                'verbose_name': 'Asociación Costo-Venta',
                'verbose_name_plural': 'Asociaciones Costo-Venta',
                'db_table': 'invoice_sales_mappings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['numero_factura'], name='sales_invoi_numero__c6358f_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['estado_facturacion'], name='sales_invoi_estado__2ec3af_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['estado_pago'], name='sales_invoi_estado__3547e1_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['fecha_vencimiento'], name='sales_invoi_fecha_v_a0861c_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['cliente', 'fecha_emision'], name='sales_invoi_cliente_693e48_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['autorizacion_sri'], name='sales_invoi_autoriz_6a07a5_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['clave_acceso'], name='sales_invoi_clave_a_839ca5_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['sales_invoice', 'estado'], name='payments_sales_i_f882dd_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['fecha_pago'], name='payments_fecha_p_d447fd_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['estado'], name='payments_estado_27283d_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['referencia'], name='payments_referen_c9caf7_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicesalesmapping',
            index=models.Index(fields=['sales_invoice'], name='invoice_sal_sales_i_67061d_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicesalesmapping',
            index=models.Index(fields=['cost_invoice'], name='invoice_sal_cost_in_540469_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='invoicesalesmapping',
            unique_together={('sales_invoice', 'cost_invoice')},
        ),
    ]
