# Generated by Django 5.1.4 on 2025-10-27 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoice',
            name='estado_facturacion',
            field=models.CharField(choices=[('facturada', 'Facturada'), ('enviada', 'Enviada al Cliente'), ('cobrada', 'Cobrada'), ('anulada', 'Anulada')], db_index=True, default='facturada', help_text='Estado de facturación', max_length=20),
        ),
    ]
