# Generated by Django 5.1.4 on 2025-10-27 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_salesinvoice_estado_facturacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesinvoice',
            name='archivo_xml',
        ),
    ]
