# Generated by Django 5.1.4 on 2025-10-27 16:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_aliases', '0007_rename_client_reso_origina_idx_client_reso_origina_a096a1_idx_and_more'),
        ('ots', '0012_ot_estado_facturacion_venta_ot_margen_bruto_and_more'),
        ('sales', '0003_remove_salesinvoice_archivo_xml'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['estado_pago', '-fecha_vencimiento'], name='sales_invoi_estado__ca7730_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['cliente', 'estado_facturacion'], name='sales_invoi_cliente_49687e_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['ot', '-fecha_emision'], name='sales_invoi_ot_id_04d0a6_idx'),
        ),
    ]
