# Generated by Django 5.1.4 on 2025-10-27 22:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_salesinvoice_sales_invoi_estado__ca7730_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='iva_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Suma total de IVA de todas las líneas', max_digits=15),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='subtotal_exento',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Suma de subtotales de líneas SIN IVA (exentas)', max_digits=15),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='subtotal_gravado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Suma de subtotales de líneas CON IVA', max_digits=15),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='iva',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto de IVA (legacy - ahora se calcula desde líneas)', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Subtotal sin IVA (legacy - ahora se calcula desde líneas)', max_digits=15, null=True),
        ),
    ]
