# Generated by Django 5.1.4 on 2025-10-27 22:16

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_salesinvoice_iva_total_salesinvoice_subtotal_exento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('numero_linea', models.PositiveIntegerField(default=1, help_text='Número de orden de la línea en la factura')),
                ('descripcion', models.CharField(help_text='Descripción detallada del servicio/producto', max_length=500)),
                ('concepto', models.CharField(choices=[('flete_local', 'Flete Local'), ('flete_maritimo', 'Flete Marítimo'), ('flete_aereo', 'Flete Aéreo'), ('flete_terrestre', 'Flete Terrestre'), ('almacenaje', 'Almacenaje'), ('handling', 'Handling / Manipulación'), ('documentacion', 'Documentación'), ('tramites_aduaneros', 'Trámites Aduaneros'), ('seguro', 'Seguro de Carga'), ('demora', 'Demora / Estadía'), ('inspeccion', 'Inspección'), ('consolidacion', 'Consolidación'), ('desconsolidacion', 'Desconsolidación'), ('embalaje', 'Embalaje'), ('etiquetado', 'Etiquetado'), ('otro', 'Otro')], db_index=True, default='otro', help_text='Concepto/categoría del cargo', max_length=50)),
                ('cantidad', models.DecimalField(decimal_places=3, default=Decimal('1.000'), help_text='Cantidad de unidades', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unidad_medida', models.CharField(default='servicio', help_text='Unidad de medida (servicio, kg, m3, contenedor, etc.)', max_length=20)),
                ('precio_unitario', models.DecimalField(decimal_places=4, help_text='Precio por unidad', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Subtotal = cantidad × precio_unitario (calculado automáticamente)', max_digits=15)),
                ('aplica_iva', models.BooleanField(db_index=True, default=True, help_text='¿Esta línea aplica IVA?')),
                ('porcentaje_iva', models.DecimalField(decimal_places=2, default=Decimal('13.00'), help_text='Porcentaje de IVA a aplicar (13% por defecto en Ecuador)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto de IVA (calculado automáticamente)', max_digits=15)),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje de descuento aplicado a esta línea', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('descuento_monto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto del descuento (calculado automáticamente)', max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total de la línea = (subtotal - descuento) + IVA (calculado automáticamente)', max_digits=15)),
                ('razon_exencion', models.CharField(blank=True, help_text="Razón de exención de IVA (ej: 'Flete internacional', 'Exportación', 'Servicio exento')", max_length=200)),
                ('codigo_exencion_sri', models.CharField(blank=True, help_text='Código de exención SRI si aplica', max_length=20)),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre esta línea')),
                ('modificado_por', models.CharField(blank=True, help_text='Usuario que modificó por última vez esta línea', max_length=100)),
                ('factura', models.ForeignKey(help_text='Factura de venta a la que pertenece este item', on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='sales.salesinvoice')),
            ],
            options={
                'verbose_name': 'Línea de Factura de Venta',
                'verbose_name_plural': 'Líneas de Facturas de Venta',
                'db_table': 'sales_invoice_items',
                'ordering': ['factura', 'numero_linea'],
                'indexes': [models.Index(fields=['factura', 'numero_linea'], name='sales_invoi_factura_01e614_idx'), models.Index(fields=['concepto'], name='sales_invoi_concept_f176d2_idx'), models.Index(fields=['aplica_iva'], name='sales_invoi_aplica__159bf6_idx'), models.Index(fields=['created_at'], name='sales_invoi_created_227def_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='sales_invoice_item_cantidad_positiva'), models.CheckConstraint(condition=models.Q(('precio_unitario__gte', 0)), name='sales_invoice_item_precio_no_negativo')],
            },
        ),
    ]
