# Generated by Django 5.1.4 on 2025-10-28 02:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_salesinvoiceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='aplica_retencion_iva',
            field=models.BooleanField(db_index=True, default=False, help_text='¿Se aplica retención de IVA 1%? (Gran Contribuyente)'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='aplica_retencion_renta',
            field=models.BooleanField(default=False, help_text='¿Se aplica retención de renta?'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='monto_neto_cobrar',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto total - retenciones = A COBRAR', max_digits=15),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='monto_retencion_iva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto retenido de IVA (1% del subtotal gravado)', max_digits=15),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='monto_retencion_renta',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto retenido de renta', max_digits=15),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='porcentaje_retencion_renta',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje de retención de renta aplicado', max_digits=5),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='tipo_documento',
            field=models.CharField(choices=[('ccf', 'Comprobante de Crédito Fiscal (CCF)'), ('factura', 'Factura de Consumidor Final'), ('factura_exportacion', 'Factura de Exportación'), ('nota_debito', 'Nota de Débito'), ('nota_credito', 'Nota de Crédito')], db_index=True, default='ccf', help_text='Tipo de documento fiscal (El Salvador)', max_length=30),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='total_retenciones',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total de retenciones (IVA + Renta)', max_digits=15),
        ),
        migrations.AddField(
            model_name='salesinvoiceitem',
            name='tipo_servicio',
            field=models.CharField(choices=[('servicio_profesional', 'Servicio Profesional (10%)'), ('servicio_tecnico', 'Servicio Técnico (10%)'), ('otros_servicios', 'Otros Servicios (5%)'), ('arrendamiento', 'Arrendamiento (10%)'), ('transporte_carga', 'Transporte de Carga (5%)'), ('comisiones', 'Comisiones (10%)'), ('venta_bienes', 'Venta de Bienes (5%)')], db_index=True, default='otros_servicios', help_text='Tipo de servicio para determinar % de retención de renta (El Salvador)', max_length=50),
        ),
    ]
