# Generated by Django 5.1.4 on 2025-11-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0020_invoice_estado_pago_invoice_monto_pagado_and_more'),
        ('sales', '0007_salesinvoice_aplica_retencion_iva_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesinvoice',
            name='iva',
        ),
        migrations.RemoveField(
            model_name='salesinvoice',
            name='subtotal',
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='cost_invoices',
            field=models.ManyToManyField(blank=True, help_text='Facturas de costo asociadas a esta factura de venta', related_name='sales_invoices_linked', to='invoices.invoice'),
        ),
    ]
