# Generated by Django 5.1.4 on 2025-11-01 22:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_aliases', '0008_clientalias_acepta_credito_fiscal_and_more'),
        ('invoices', '0020_invoice_estado_pago_invoice_monto_pagado_and_more'),
        ('ots', '0012_ot_estado_facturacion_venta_ot_margen_bruto_and_more'),
        ('sales', '0008_remove_salesinvoice_iva_remove_salesinvoice_subtotal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoice',
            name='numero_factura',
            field=models.CharField(db_index=True, help_text='Número de factura de venta del sistema externo', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='salesinvoice',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('numero_factura',), name='unique_numero_factura_active'),
        ),
    ]
