# Generated by Django 5.1.4 on 2025-11-01 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_alter_salesinvoice_numero_factura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='tipo_operacion',
            field=models.CharField(choices=[('nacional', 'Operación Nacional'), ('internacional', 'Operación Internacional')], db_index=True, default='nacional', help_text='Tipo de operación: nacional (con IVA) o internacional (sin IVA)', max_length=20),
        ),
    ]
