# Generated by Django 5.1.4 on 2025-11-02 00:22

import common.storage_backends
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_salesinvoice_tipo_operacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoice',
            name='estado_facturacion',
            field=models.CharField(choices=[('facturada', 'Facturada'), ('pendiente_cobro', 'Pendiente de Cobro'), ('pagada', 'Pagada'), ('anulada_parcial', 'Anulada Parcialmente'), ('anulada', 'Anulada')], db_index=True, default='facturada', help_text='Estado de facturación', max_length=20),
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('numero_nota_credito', models.CharField(db_index=True, help_text='Número de la nota de crédito', max_length=50, unique=True)),
                ('fecha_emision', models.DateField(help_text='Fecha de emisión de la nota de crédito')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto de la nota de crédito', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('motivo', models.TextField(help_text='Motivo de la nota de crédito')),
                ('archivo_pdf', models.FileField(blank=True, help_text='PDF de la nota de crédito', null=True, storage=common.storage_backends.CloudinaryMediaStorage(), upload_to='credit_notes/')),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre la nota de crédito')),
                ('sales_invoice', models.ForeignKey(help_text='Factura de venta a la que se aplica esta nota de crédito', on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='sales.salesinvoice')),
            ],
            options={
                'verbose_name': 'Nota de Crédito',
                'verbose_name_plural': 'Notas de Crédito',
                'db_table': 'sales_credit_notes',
                'ordering': ['-fecha_emision', '-created_at'],
                'indexes': [models.Index(fields=['sales_invoice', '-fecha_emision'], name='sales_credi_sales_i_278c13_idx'), models.Index(fields=['numero_nota_credito'], name='sales_credi_numero__4e3cee_idx')],
            },
        ),
    ]
