# Generated by Django 5.1.4 on 2025-10-04 21:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0001_initial'),
        ('client_aliases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('numero_ot', models.CharField(db_index=True, help_text='Número único de la orden de trabajo (ej: OT-2024-0001)', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='El número de OT debe contener solo letras mayúsculas, números y guiones', regex='^[A-Z0-9\\-]+$')])),
                ('master_bl', models.CharField(blank=True, db_index=True, help_text='Número del Master BL (conocimiento de embarque principal)', max_length=50, null=True)),
                ('house_bls', models.JSONField(blank=True, default=list, help_text="Lista de House BLs asociados a esta OT. Formato: ['HBL001', 'HBL002']")),
                ('contenedores', models.JSONField(blank=True, default=list, help_text="Lista de contenedores con su información. Formato: [{'numero': 'MSCU1234567', 'tipo': '40HC', 'peso': 25000, 'sello': 'SEAL123'}]")),
                ('fecha_eta', models.DateField(blank=True, help_text='Fecha estimada de llegada (Estimated Time of Arrival)', null=True)),
                ('fecha_llegada', models.DateField(blank=True, help_text='Fecha real de llegada', null=True)),
                ('puerto_origen', models.CharField(blank=True, help_text='Puerto de origen de la carga', max_length=100)),
                ('puerto_destino', models.CharField(blank=True, help_text='Puerto de destino de la carga', max_length=100)),
                ('provision_hierarchy', models.JSONField(blank=True, default=dict, help_text="Jerarquía de provisiones de costos. Formato: {'total': 5000, 'items': [{'concepto': 'Flete', 'monto': 3000}, ...]}")),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_transito', 'En Tránsito'), ('puerto', 'En Puerto'), ('entregado', 'Entregado'), ('facturado', 'Facturado'), ('cerrado', 'Cerrado'), ('cancelado', 'Cancelado')], db_index=True, default='pendiente', help_text='Estado actual de la OT', max_length=20)),
                ('notas', models.TextField(blank=True, help_text='Notas o comentarios sobre esta OT')),
                ('cliente', models.ForeignKey(help_text='Cliente al que pertenece esta carga', on_delete=django.db.models.deletion.PROTECT, related_name='ots', to='client_aliases.clientalias')),
                ('modificado_por', models.ForeignKey(blank=True, help_text='Último usuario que modificó esta OT', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ots_modificadas', to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(help_text='Proveedor/transportista que emite esta OT', on_delete=django.db.models.deletion.PROTECT, related_name='ots', to='catalogs.provider')),
            ],
            options={
                'verbose_name': 'Orden de Trabajo',
                'verbose_name_plural': 'Órdenes de Trabajo',
                'db_table': 'ots',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['numero_ot'], name='ots_numero__dbbf5e_idx'), models.Index(fields=['master_bl'], name='ots_master__480746_idx'), models.Index(fields=['estado'], name='ots_estado_138c29_idx'), models.Index(fields=['proveedor', 'estado'], name='ots_proveed_32240c_idx'), models.Index(fields=['cliente'], name='ots_cliente_5972b0_idx'), models.Index(fields=['-created_at'], name='ots_created_af722c_idx')],
            },
        ),
    ]
