# Generated by Django 5.1.4 on 2025-10-04 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0001_initial'),
        ('ots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ot',
            name='barco',
            field=models.CharField(blank=True, default='-', help_text='Nombre del barco/buque', max_length=200),
        ),
        migrations.AddField(
            model_name='ot',
            name='comentarios',
            field=models.TextField(blank=True, default='', help_text='Comentarios adicionales (solo edición manual)'),
        ),
        migrations.AddField(
            model_name='ot',
            name='contra_entrega_fecha',
            field=models.DateField(blank=True, help_text='Fecha de Contra Entrega', null=True),
        ),
        migrations.AddField(
            model_name='ot',
            name='contra_entrega_tipo',
            field=models.CharField(blank=True, default='-', help_text='Tipo de Contra Entrega', max_length=50),
        ),
        migrations.AddField(
            model_name='ot',
            name='envio_cierre_ot',
            field=models.DateField(blank=True, help_text='Fecha de envío de cierre de OT', null=True),
        ),
        migrations.AddField(
            model_name='ot',
            name='estado_facturado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('facturado', 'Facturado')], default='pendiente', help_text='Estado de facturación (calculado automáticamente)', max_length=20),
        ),
        migrations.AddField(
            model_name='ot',
            name='estado_provision',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('provisionada', 'Provisionada'), ('revision', 'En Revisión'), ('disputada', 'Disputada')], default='pendiente', help_text='Estado de provisión (calculado automáticamente o seteable por admin)', max_length=20),
        ),
        migrations.AddField(
            model_name='ot',
            name='etd',
            field=models.DateField(blank=True, help_text='Estimated Time of Departure - Fecha estimada de salida', null=True),
        ),
        migrations.AddField(
            model_name='ot',
            name='express_release_fecha',
            field=models.DateField(blank=True, help_text='Fecha de Express Release', null=True),
        ),
        migrations.AddField(
            model_name='ot',
            name='express_release_tipo',
            field=models.CharField(blank=True, default='-', help_text='Tipo de Express Release', max_length=50),
        ),
        migrations.AddField(
            model_name='ot',
            name='fecha_provision',
            field=models.DateField(blank=True, help_text='Fecha de la provisión de proveedor', null=True),
        ),
        migrations.AddField(
            model_name='ot',
            name='fecha_recepcion_factura',
            field=models.DateField(blank=True, help_text='Fecha en que se recibió la factura', null=True),
        ),
        migrations.AddField(
            model_name='ot',
            name='fecha_solicitud_facturacion',
            field=models.DateField(blank=True, help_text='Fecha en que se solicitó la facturación', null=True),
        ),
        migrations.AddField(
            model_name='ot',
            name='operativo',
            field=models.CharField(blank=True, default='-', help_text='Nombre del operativo asignado (inferido del archivo o asignado manualmente)', max_length=100),
        ),
        migrations.AddField(
            model_name='ot',
            name='provision_locked',
            field=models.BooleanField(default=False, help_text='Si está bloqueada, no puede ser sobrescrita por importaciones de menor prioridad'),
        ),
        migrations.AddField(
            model_name='ot',
            name='provision_source',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('csv', 'CSV'), ('excel', 'Excel')], default='', help_text='Fuente de la provisión (MANUAL, CSV, EXCEL)', max_length=20),
        ),
        migrations.AddField(
            model_name='ot',
            name='provision_updated_by',
            field=models.CharField(blank=True, default='', help_text='Usuario o sistema que actualizó la provisión', max_length=200),
        ),
        migrations.AddField(
            model_name='ot',
            name='tipo_embarque',
            field=models.CharField(blank=True, default='-', help_text='Tipo de embarque (FCL, LCL, etc.)', max_length=50),
        ),
        migrations.AlterField(
            model_name='ot',
            name='proveedor',
            field=models.ForeignKey(blank=True, help_text='Proveedor/transportista que emite esta OT (opcional)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ots', to='catalogs.provider'),
        ),
    ]
