# Generated by Django 5.1.4 on 2025-10-04 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ots', '0002_ot_barco_ot_comentarios_ot_contra_entrega_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ot',
            name='contra_entrega_tipo',
            field=models.CharField(blank=True, default='-', help_text='Tipo de Contra Entrega', max_length=150),
        ),
        migrations.AlterField(
            model_name='ot',
            name='express_release_tipo',
            field=models.CharField(blank=True, default='-', help_text='Tipo de Express Release', max_length=150),
        ),
    ]
