# Generated by Django 5.1.4 on 2025-10-05 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ots', '0004_alter_ot_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ot',
            name='estado',
            field=models.CharField(choices=[('almacenadora', 'Almacenadora'), ('bodega', 'Bodega'), ('cerrada', 'Cerrada'), ('desprendimiento', 'Desprendimiento'), ('disputa', 'Disputa'), ('en_rada', 'En Rada'), ('fact_adicionales', 'Fact Adicionales'), ('finalizada', 'Finalizada'), ('puerto', 'Puerto'), ('transito', 'Tránsito'), ('pendiente', 'Pendiente'), ('entregado', 'Entregado'), ('facturado', 'Facturado'), ('cerrado', 'Cerrado'), ('cancelado', 'Cancelado')], db_index=True, default='transito', help_text='Estado actual de la OT', max_length=30),
        ),
    ]
