# Generated by Django 5.1.4 on 2025-10-05 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ots', '0006_ot_tipo_operacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ot',
            name='master_bl',
            field=models.CharField(blank=True, db_index=True, help_text='Número del Master BL (conocimiento de embarque principal)', max_length=255, null=True),
        ),
    ]
