# Generated by Django 5.1.4 on 2025-10-11 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ots', '0007_increase_master_bl_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ot',
            name='contenedores',
            field=models.JSONField(blank=True, default=list, help_text="Lista de números de contenedores. Formato: ['MSCU1234567', 'MSCU7654321']"),
        ),
    ]
