# Generated by Django 5.1.4 on 2025-10-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ots', '0009_processedfile'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='processedfile',
            new_name='processed_f_file_ha_3eec82_idx',
            old_name='processed_f_file_ha_idx',
        ),
        migrations.RenameIndex(
            model_name='processedfile',
            new_name='processed_f_created_15746d_idx',
            old_name='processed_f_created_idx',
        ),
        migrations.AddField(
            model_name='ot',
            name='barco_source',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('csv', 'CSV'), ('excel', 'Excel')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='ot',
            name='estado_source',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('csv', 'CSV'), ('excel', 'Excel')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='ot',
            name='fecha_eta_source',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('csv', 'CSV'), ('excel', 'Excel')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='ot',
            name='fecha_llegada_source',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('csv', 'CSV'), ('excel', 'Excel')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='ot',
            name='proveedor_source',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('csv', 'CSV'), ('excel', 'Excel')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='ot',
            name='puerto_destino_source',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('csv', 'CSV'), ('excel', 'Excel')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='ot',
            name='puerto_origen_source',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('csv', 'CSV'), ('excel', 'Excel')], default='', max_length=20),
        ),
    ]
