# Generated by Django 5.1.4 on 2025-10-14 19:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0008_rename_catalogs_co_categor_285528_idx_catalogs_co_categor_7fab5a_idx'),
        ('client_aliases', '0007_rename_client_reso_origina_idx_client_reso_origina_a096a1_idx_and_more'),
        ('ots', '0010_rename_processed_f_file_ha_idx_processed_f_file_ha_3eec82_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ot',
            name='row_hash',
            field=models.CharField(blank=True, db_index=True, help_text='SHA256 hash of the row data to detect changes.', max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='ot',
            index=models.Index(fields=['row_hash'], name='ots_row_has_6b4c8c_idx'),
        ),
    ]
