# Generated by Django 5.1.4 on 2025-10-25 03:39

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ots', '0011_ot_row_hash_ot_ots_row_has_6b4c8c_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='ot',
            name='estado_facturacion_venta',
            field=models.CharField(choices=[('sin_facturar', 'Sin Facturar'), ('facturado_parcial', 'Facturado Parcialmente'), ('facturado_total', 'Facturado Totalmente')], db_index=True, default='sin_facturar', help_text='Estado de facturación de venta (calculado automáticamente)', max_length=20),
        ),
        migrations.AddField(
            model_name='ot',
            name='margen_bruto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto vendido - suma de costos (auto-calculado)', max_digits=15),
        ),
        migrations.AddField(
            model_name='ot',
            name='monto_total_costos',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Suma de todas las facturas de costo asociadas (auto-calculado)', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='ot',
            name='monto_total_vendido',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Suma de todas las facturas de venta asociadas (auto-calculado)', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='ot',
            name='porcentaje_margen',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje de margen sobre ventas (auto-calculado)', max_digits=6),
        ),
    ]
