# Generated by Django 5.1.4 on 2025-10-04 22:46

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0001_initial'),
        ('ots', '0003_alter_ot_contra_entrega_tipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(help_text='Nombre original del archivo', max_length=500)),
                ('path', models.CharField(help_text='Ruta relativa del archivo en el storage', max_length=1024)),
                ('sha256', models.CharField(db_index=True, help_text='Hash SHA256 del archivo para deduplicación', max_length=64, unique=True)),
                ('size', models.BigIntegerField(help_text='Tamaño del archivo en bytes')),
                ('content_type', models.CharField(help_text='MIME type del archivo (application/pdf, application/json, etc.)', max_length=100)),
            ],
            options={
                'db_table': 'invoices_uploaded_file',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sha256'], name='invoices_up_sha256_892421_idx'), models.Index(fields=['-created_at'], name='invoices_up_created_df408c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('ot_number', models.CharField(blank=True, db_index=True, default='', help_text='Número de OT denormalizado para búsquedas rápidas', max_length=32)),
                ('proveedor_nit', models.CharField(blank=True, default='', help_text='NIT del proveedor', max_length=64)),
                ('proveedor_nombre', models.CharField(help_text='Nombre del proveedor (texto libre)', max_length=255)),
                ('tipo_proveedor', models.CharField(choices=[('naviera', 'Naviera'), ('transporte_local', 'Transporte Local'), ('aduana', 'Aduana'), ('agente_carga', 'Agente de Carga'), ('otro', 'Otro')], default='otro', help_text='Tipo de proveedor', max_length=32)),
                ('proveedor_categoria', models.CharField(choices=[('local', 'Local'), ('internacional', 'Internacional')], default='local', help_text='Categoría del proveedor', max_length=32)),
                ('numero_factura', models.CharField(db_index=True, help_text='Número único de la factura', max_length=64, unique=True)),
                ('fecha_emision', models.DateField(db_index=True, help_text='Fecha de emisión de la factura')),
                ('fecha_vencimiento', models.DateField(blank=True, help_text='Fecha de vencimiento (si aplica)', null=True)),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto de la factura en USD', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('tipo_costo', models.CharField(choices=[('FLETE', 'Flete'), ('TRANSPORTE', 'Transporte'), ('ADUANA', 'Aduana'), ('ALMACENAJE', 'Almacenaje'), ('DEMORA', 'Demora'), ('OTRO', 'Otro')], default='OTRO', help_text='Tipo de costo', max_length=32)),
                ('referencias_detectadas', models.JSONField(blank=True, default=dict, help_text='Referencias detectadas: {mbl, contenedor, ot, barco, fecha_eta, etc.}')),
                ('confianza_match', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Nivel de confianza del matching (0.000 - 1.000)', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('assignment_method', models.CharField(blank=True, choices=[('ot_directa', 'OT Directa'), ('mbl_contenedor', 'MBL + Contenedor'), ('solo_mbl', 'Solo MBL'), ('solo_contenedor', 'Solo Contenedor'), ('proveedor_fecha', 'Proveedor + Fecha'), ('manual', 'Asignación Manual'), ('no_match', 'Sin Match')], default='', help_text='Método usado para asignar la OT', max_length=32)),
                ('requiere_revision', models.BooleanField(default=True, help_text='Indica si requiere revisión manual')),
                ('estado_provision', models.CharField(choices=[('pendiente', 'Pendiente'), ('provisionada', 'Provisionada'), ('rechazada', 'Rechazada')], default='pendiente', help_text='Estado de la provisión', max_length=32)),
                ('fecha_provision', models.DateField(blank=True, help_text='Fecha en que se provisionó', null=True)),
                ('estado_facturacion', models.CharField(choices=[('pendiente', 'Pendiente'), ('facturada', 'Facturada')], default='pendiente', help_text='Estado de facturación', max_length=32)),
                ('fecha_facturacion', models.DateField(blank=True, help_text='Fecha en que se facturó', null=True)),
                ('processed_at', models.DateTimeField(blank=True, help_text='Fecha y hora de procesamiento', null=True)),
                ('processed_by', models.CharField(default='system', help_text='Usuario o sistema que procesó la factura', max_length=255)),
                ('processing_source', models.CharField(choices=[('email_auto', 'Email Automático'), ('upload_manual', 'Upload Manual'), ('csv_import', 'Importación CSV')], default='upload_manual', help_text='Origen del procesamiento', max_length=32)),
                ('notas', models.TextField(blank=True, default='', help_text='Notas adicionales')),
                ('ot', models.ForeignKey(blank=True, help_text='OT asociada a esta factura', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='ots.ot')),
                ('proveedor', models.ForeignKey(blank=True, help_text='Proveedor del catálogo (si existe)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='catalogs.provider')),
                ('uploaded_file', models.OneToOneField(help_text='Archivo original de la factura', on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='invoices.uploadedfile')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'db_table': 'invoices_invoice',
                'ordering': ['-fecha_emision', '-created_at'],
                'indexes': [models.Index(fields=['numero_factura'], name='invoices_in_numero__ded780_idx'), models.Index(fields=['ot_number'], name='invoices_in_ot_numb_808576_idx'), models.Index(fields=['-fecha_emision'], name='invoices_in_fecha_e_dd9e20_idx'), models.Index(fields=['estado_provision'], name='invoices_in_estado__b67700_idx'), models.Index(fields=['requiere_revision'], name='invoices_in_requier_5c20b4_idx'), models.Index(fields=['-created_at'], name='invoices_in_created_67cbdc_idx')],
            },
        ),
    ]
