# Generated by Django 5.1.4 on 2025-10-06 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0002_provider_dias_credito_provider_notas_credito_and_more'),
        ('invoices', '0002_update_estado_provision_choices'),
        ('ots', '0007_increase_master_bl_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='alerta_vencimiento',
            field=models.BooleanField(db_index=True, default=False, help_text='Alerta si está próxima a vencer (7 días)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='dias_credito_aplicado',
            field=models.PositiveIntegerField(default=0, help_text='Días de crédito aplicados desde el proveedor'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tipo_pago',
            field=models.CharField(choices=[('contado', 'Contado'), ('credito', 'Crédito')], db_index=True, default='contado', help_text='Tipo de pago: contado o crédito', max_length=16),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, db_index=True, help_text='Fecha de vencimiento calculada (fecha_emision + dias_credito_aplicado)', null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tipo_costo',
            field=models.CharField(choices=[('FLETE', 'Flete'), ('CARGOS_NAVIERA', 'Cargos de Naviera'), ('TRANSPORTE', 'Transporte'), ('ADUANA', 'Aduana'), ('ALMACENAJE', 'Almacenaje'), ('DEMORA', 'Demora'), ('OTRO', 'Otro')], default='OTRO', help_text='Tipo de costo', max_length=32),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['tipo_pago'], name='invoices_in_tipo_pa_b44bdb_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['fecha_vencimiento'], name='invoices_in_fecha_v_2851b5_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['alerta_vencimiento'], name='invoices_in_alerta__3e6200_idx'),
        ),
    ]
