# Generated by Django 5.1.4 on 2025-10-11 18:58

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0007_remove_category_old_field'),
        ('invoices', '0003_invoice_alerta_vencimiento_and_more'),
        ('ots', '0008_alter_ot_contenedores'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('numero_nota', models.CharField(db_index=True, help_text='Número único de la nota de crédito', max_length=64, unique=True)),
                ('proveedor_nombre', models.CharField(help_text='Nombre del proveedor (denormalizado)', max_length=255)),
                ('fecha_emision', models.DateField(db_index=True, help_text='Fecha de emisión de la nota de crédito')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto de la nota de crédito (SIEMPRE NEGATIVO)', max_digits=12)),
                ('motivo', models.TextField(help_text='Motivo de la emisión de la nota de crédito')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Aplicar'), ('aplicada', 'Aplicada'), ('rechazada', 'Rechazada')], db_index=True, default='pendiente', help_text='Estado de la nota de crédito', max_length=32)),
                ('fecha_aplicacion', models.DateField(blank=True, help_text='Fecha en que se aplicó la nota de crédito', null=True)),
                ('notas', models.TextField(blank=True, default='', help_text='Notas adicionales sobre la nota de crédito')),
                ('referencias_detectadas', models.JSONField(blank=True, default=dict, help_text='Referencias detectadas: {numero_factura, monto, etc.}')),
                ('processed_at', models.DateTimeField(blank=True, help_text='Fecha y hora de procesamiento', null=True)),
                ('processed_by', models.CharField(default='system', help_text='Usuario o sistema que procesó la nota', max_length=255)),
                ('processing_source', models.CharField(choices=[('upload_auto', 'Upload Automático'), ('upload_manual', 'Upload Manual'), ('manual_entry', 'Entrada Manual')], default='upload_manual', help_text='Origen del procesamiento', max_length=32)),
                ('invoice_relacionada', models.ForeignKey(blank=True, help_text='Factura a la que se aplica la nota de crédito (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_credito', to='invoices.invoice')),
                ('proveedor', models.ForeignKey(help_text='Proveedor que emitió la nota de crédito', on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='catalogs.provider')),
                ('uploaded_file', models.OneToOneField(blank=True, help_text='Archivo original de la nota de crédito (PDF)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_note', to='invoices.uploadedfile')),
            ],
            options={
                'verbose_name': 'Nota de Crédito',
                'verbose_name_plural': 'Notas de Crédito',
                'db_table': 'invoices_credit_note',
                'ordering': ['-fecha_emision', '-created_at'],
                'indexes': [models.Index(fields=['numero_nota'], name='invoices_cr_numero__798eb6_idx'), models.Index(fields=['-fecha_emision'], name='invoices_cr_fecha_e_b6013f_idx'), models.Index(fields=['estado'], name='invoices_cr_estado_2e5b03_idx'), models.Index(fields=['-created_at'], name='invoices_cr_created_2beab6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('codigo', models.CharField(db_index=True, help_text='Código único de la disputa (auto-generado)', max_length=32, unique=True)),
                ('tipo_disputa', models.CharField(choices=[('cantidad', 'Cantidad Incorrecta'), ('servicio', 'Servicio No Prestado'), ('duplicada', 'Factura Duplicada'), ('precio', 'Precio Incorrecto'), ('otro', 'Otro')], help_text='Tipo de disputa', max_length=32)),
                ('detalle', models.TextField(help_text='Descripción detallada de la disputa')),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('en_revision', 'En Revisión'), ('resuelta', 'Resuelta'), ('cerrada', 'Cerrada')], db_index=True, default='abierta', help_text='Estado actual de la disputa', max_length=32)),
                ('monto_disputa', models.DecimalField(decimal_places=2, help_text='Monto en disputa (USD)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('fecha_resolucion', models.DateField(blank=True, help_text='Fecha en que se resolvió la disputa', null=True)),
                ('resolucion', models.TextField(blank=True, default='', help_text='Descripción de cómo se resolvió la disputa')),
                ('notas', models.TextField(blank=True, default='', help_text='Notas adicionales sobre la disputa')),
                ('invoice', models.ForeignKey(help_text='Factura relacionada con la disputa', on_delete=django.db.models.deletion.CASCADE, related_name='disputas', to='invoices.invoice')),
                ('ot', models.ForeignKey(blank=True, help_text='OT relacionada (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputas', to='ots.ot')),
            ],
            options={
                'verbose_name': 'Disputa',
                'verbose_name_plural': 'Disputas',
                'db_table': 'invoices_dispute',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['codigo'], name='invoices_di_codigo_035adc_idx'), models.Index(fields=['estado'], name='invoices_di_estado_7c0360_idx'), models.Index(fields=['-created_at'], name='invoices_di_created_51e665_idx')],
            },
        ),
    ]
