# Generated by Django 5.1.4 on 2025-10-11 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_creditnote_dispute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispute',
            name='tipo_disputa',
            field=models.CharField(choices=[('flete', 'Flete'), ('cargos_naviera', 'Cargos de Naviera'), ('cantidad', 'Cantidad Incorrecta'), ('servicio', 'Servicio No Prestado'), ('duplicada', 'Factura Duplicada'), ('precio', 'Diferencias de Valor'), ('otro', 'Otro')], help_text='Tipo de disputa', max_length=32),
        ),
    ]
