# Generated by Django 5.1.4 on 2025-10-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_alter_dispute_tipo_disputa'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='monto_original',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto original de la factura antes de aplicar notas de crédito', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='estado_provision',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('provisionada', 'Provisionada'), ('revision', 'En Revisión'), ('disputada', 'Disputada'), ('rechazada', 'Rechazada (Legacy)'), ('anulada', 'Anulada'), ('anulada_parcialmente', 'Anulada Parcialmente')], default='pendiente', help_text='Estado de la provisión', max_length=32),
        ),
    ]
