# Generated by Django 5.1.4 on 2025-10-11 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_invoice_monto_original_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='numero_caso',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Número de caso externo (ej: caso con proveedor, naviera, etc.)', max_length=64),
        ),
        migrations.CreateModel(
            name='DisputeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo_evento', models.CharField(choices=[('creacion', 'Creación'), ('actualizacion', 'Actualización'), ('comentario', 'Comentario'), ('cambio_estado', 'Cambio de Estado'), ('resolucion', 'Resolución'), ('archivo_adjunto', 'Archivo Adjunto')], help_text='Tipo de evento', max_length=32)),
                ('descripcion', models.TextField(help_text='Descripción del evento')),
                ('usuario', models.CharField(blank=True, default='', help_text='Usuario que generó el evento', max_length=255)),
                ('metadata', models.JSONField(blank=True, help_text='Datos adicionales del evento (JSON)', null=True)),
                ('dispute', models.ForeignKey(help_text='Disputa relacionada', on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='invoices.dispute')),
            ],
            options={
                'verbose_name': 'Evento de Disputa',
                'verbose_name_plural': 'Eventos de Disputas',
                'db_table': 'invoices_dispute_event',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['dispute', '-created_at'], name='invoices_di_dispute_469716_idx')],
            },
        ),
    ]
