# Generated by Django 5.1.4 on 2025-10-11 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_dispute_numero_caso_disputeevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispute',
            name='numero_caso',
            field=models.CharField(db_index=True, help_text='Número de caso externo (ej: caso con proveedor, naviera, etc.)', max_length=64),
        ),
    ]
