# Generated by Django 5.1.4 on 2025-10-11 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_alter_dispute_numero_caso'),
        ('ots', '0008_alter_ot_contenedores'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='dispute',
            name='invoices_di_codigo_035adc_idx',
        ),
        migrations.RemoveField(
            model_name='dispute',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='disputeevent',
            name='tipo_evento',
        ),
        migrations.AddField(
            model_name='dispute',
            name='operativo',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Nombre del operativo responsable de la disputa', max_length=255),
        ),
        migrations.AddField(
            model_name='disputeevent',
            name='monto_recuperado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto recuperado (si aplica)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='disputeevent',
            name='tipo',
            field=models.CharField(choices=[('creacion', 'Creación'), ('actualizacion', 'Actualización'), ('comentario', 'Comentario'), ('cambio_estado', 'Cambio de Estado'), ('resolucion', 'Resolución'), ('archivo_adjunto', 'Archivo Adjunto')], default='comentario', help_text='Tipo de evento', max_length=32),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['numero_caso'], name='invoices_di_numero__f17384_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['operativo'], name='invoices_di_operati_2deddd_idx'),
        ),
    ]
