# Generated by Django 5.1.4 on 2025-10-14 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0012_populate_monto_aplicable'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='invoice',
            name='invoices_in_monto_a_idx',
        ),
        migrations.RenameIndex(
            model_name='dispute',
            new_name='invoices_di_resulta_d1b5bc_idx',
            old_name='invoices_di_resulta_idx',
        ),
        migrations.AlterField(
            model_name='disputeevent',
            name='tipo',
            field=models.CharField(choices=[('creacion', 'Creación'), ('actualizacion', 'Actualización'), ('comentario', 'Comentario'), ('cambio_estado', 'Cambio de Estado'), ('resolucion', 'Resolución'), ('archivo_adjunto', 'Archivo Adjunto')], help_text='Tipo de evento', max_length=32),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='estado_provision',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('revision', 'En Revisión'), ('disputada', 'Disputada'), ('provisionada', 'Provisionada'), ('anulada', 'Anulada'), ('anulada_parcialmente', 'Anulada Parcialmente'), ('rechazada', 'Rechazada')], default='pendiente', help_text='Estado de la provisión', max_length=32),
        ),
    ]
