# Generated by Django 5.1.4 on 2025-10-17 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0013_remove_invoice_invoices_in_monto_a_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnote',
            name='motivo',
            field=models.TextField(blank=True, default='', help_text='Motivo de la emisión de la nota de crédito'),
        ),
    ]
