# Generated by Django 5.1.4 on 2025-10-18 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0011_fix_unique_constraint_for_soft_delete'),
        ('invoices', '0014_alter_creditnote_motivo'),
        ('ots', '0011_ot_row_hash_ot_ots_row_has_6b4c8c_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='numero_factura',
            field=models.CharField(db_index=True, help_text='Número único de la factura (único solo entre facturas no eliminadas)', max_length=64),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('numero_factura',), name='unique_numero_factura_not_deleted'),
        ),
    ]
