# Generated by Django 5.1.4 on 2025-10-18 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0012_fix_unique_constraint_creditnote'),
        ('invoices', '0015_fix_unique_constraint_for_soft_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnote',
            name='numero_nota',
            field=models.CharField(db_index=True, help_text='Número único de la nota de crédito (único solo entre notas no eliminadas)', max_length=64),
        ),
        migrations.AddConstraint(
            model_name='creditnote',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('numero_nota',), name='unique_numero_nota_not_deleted'),
        ),
    ]
