# Generated by Django 5.1.4 on 2025-10-19 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0017_fix_uploaded_file_unique_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispute',
            name='tipo_disputa',
            field=models.CharField(choices=[('servicio_no_prestado', 'Servicio No Prestado'), ('almacenaje_no_aplica', 'Almacenaje No Aplica'), ('dias_libres_incorrectos', 'No Se Están Aplicando Correctamente Los Días Libres'), ('cargo_no_aplica', 'Cargo No Aplica'), ('demoras_no_aplican', 'Demoras No Aplican'), ('otro', 'Otro')], help_text='Tipo de disputa', max_length=32),
        ),
    ]
