# Generated by Django 5.1.4 on 2025-10-24 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0018_update_dispute_tipo_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='tipo_costo',
            field=models.CharField(db_index=True, default='OTRO', help_text='Tipo de costo (código desde catálogo CostType)', max_length=50),
        ),
    ]
