# Generated by Django 5.1.4 on 2025-10-25 18:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0019_update_tipo_costo_dynamic'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Pago'), ('pagado_parcial', 'Pagado Parcialmente'), ('pagado_total', 'Pagado Totalmente')], db_index=True, default='pendiente', help_text='Estado de pago a proveedor', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto total pagado a este proveedor por esta factura', max_digits=15),
        ),
        migrations.AddField(
            model_name='invoice',
            name='monto_pendiente',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto pendiente de pago (calculado automáticamente)', max_digits=15),
        ),
    ]
