# Generated by Django 5.1.4 on 2025-11-03 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0020_invoice_estado_pago_invoice_monto_pagado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='tipo_proveedor',
            field=models.CharField(choices=[('naviera', 'Naviera'), ('agente_local', 'Agente Local'), ('agencia_aduanal', 'Agencia Aduanal'), ('agente_origen', 'Agente de Origen'), ('aseguradora', 'Aseguradora'), ('aerolinea', 'Aerolínea'), ('consolidadora', 'Consolidadora'), ('almacenadora', 'Almacenadora'), ('transportista', 'Transportista'), ('otro', 'Otro')], default='otro', help_text='Tipo de proveedor', max_length=32),
        ),
    ]
