# Generated by Django 5.1.4 on 2025-11-03 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0018_fix_uploaded_file_constraint_cleanup'),
        ('invoices', '0021_alter_invoice_tipo_proveedor'),
    ]

    operations = [
        # Merge migration - no operations needed
    ]
