# Generated by Django 5.1.4 on 2025-11-04 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0025_fix_pattern_unique_constraint'),
        ('invoices', '0022_merge_migrations'),
        ('ots', '0012_ot_estado_facturacion_venta_ot_margen_bruto_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='invoice',
            name='unique_numero_factura_not_deleted',
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('numero_factura', 'proveedor'), name='unique_numero_factura_proveedor_not_deleted'),
        ),
    ]
