# Generated by Django 5.1.4 on 2025-11-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0023_change_unique_constraint_to_numero_factura_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='fecha_disputa',
            field=models.DateField(blank=True, help_text='Fecha en que se reportó/aperturó la disputa (puede ser diferente a la fecha de creación del registro)', null=True),
        ),
    ]
