# Generated by Django 5.1.4 on 2025-10-04 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('original_name', models.CharField(help_text='Nombre exacto como aparece en el documento (Excel, factura, etc)', max_length=500)),
                ('normalized_name', models.CharField(db_index=True, help_text='Versión normalizada para búsquedas (uppercase, sin puntuación extra)', max_length=500)),
                ('country', models.CharField(blank=True, help_text='Código ISO del país (GT, SV, NI, etc) - ayuda a diferenciar empresas similares', max_length=3, null=True)),
                ('notes', models.TextField(blank=True, help_text='Notas del administrador sobre este cliente')),
                ('is_verified', models.BooleanField(default=False, help_text='Si un admin revisó y confirmó que este alias es correcto/único')),
                ('verified_at', models.DateTimeField(blank=True, help_text='Cuándo fue verificado', null=True)),
                ('usage_count', models.IntegerField(default=0, help_text='Cuántas veces apareció este cliente en documentos')),
                ('merged_into', models.ForeignKey(blank=True, help_text='Si este alias fue fusionado, referencia al alias principal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_aliases', to='client_aliases.clientalias')),
                ('provider', models.ForeignKey(blank=True, help_text='Proveedor que reportó este cliente (útil para contexto)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_aliases', to='catalogs.provider')),
                ('verified_by', models.ForeignKey(blank=True, help_text='Usuario que verificó este alias', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alias de Cliente',
                'verbose_name_plural': 'Aliases de Clientes',
                'db_table': 'client_aliases',
                'ordering': ['-usage_count', 'normalized_name'],
            },
        ),
        migrations.CreateModel(
            name='SimilarityMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('similarity_score', models.FloatField(help_text='Score de similitud calculado por fuzzy matching (0-100)')),
                ('detection_method', models.CharField(default='fuzzywuzzy', help_text='Algoritmo usado para detectar similitud', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pendiente de Revisión'), ('approved', 'Aprobado - Fusionado'), ('rejected', 'Rechazado - Son Diferentes'), ('ignored', 'Ignorado - Revisar Después')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, help_text='Por qué se aprobó o rechazó')),
                ('alias_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_matches_as_first', to='client_aliases.clientalias')),
                ('alias_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_matches_as_second', to='client_aliases.clientalias')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_similarities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sugerencia de Similitud',
                'verbose_name_plural': 'Sugerencias de Similitud',
                'db_table': 'similarity_matches',
                'ordering': ['-similarity_score', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='clientalias',
            index=models.Index(fields=['normalized_name'], name='client_alia_normali_d1e746_idx'),
        ),
        migrations.AddIndex(
            model_name='clientalias',
            index=models.Index(fields=['country', 'normalized_name'], name='client_alia_country_c8de2e_idx'),
        ),
        migrations.AddIndex(
            model_name='clientalias',
            index=models.Index(fields=['is_verified'], name='client_alia_is_veri_2537fd_idx'),
        ),
        migrations.AddIndex(
            model_name='similaritymatch',
            index=models.Index(fields=['status'], name='similarity__status_b2ad85_idx'),
        ),
        migrations.AddIndex(
            model_name='similaritymatch',
            index=models.Index(fields=['similarity_score'], name='similarity__similar_e20825_idx'),
        ),
        migrations.AddIndex(
            model_name='similaritymatch',
            index=models.Index(fields=['-similarity_score', 'status'], name='similarity__similar_95039b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='similaritymatch',
            unique_together={('alias_1', 'alias_2')},
        ),
    ]
