# Generated by Django 5.1.4 on 2025-10-09 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_aliases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientalias',
            name='short_name',
            field=models.CharField(blank=True, db_index=True, help_text="Alias corto para usar en nombres de archivos (ej: 'SIMAN', 'WALMART', 'PRICESMART')", max_length=50, null=True, unique=True),
        ),
    ]
