# Generated by Django 5.1.4 on 2025-10-11 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_aliases', '0002_clientalias_short_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientalias',
            name='country',
        ),
    ]
