# Generated by Django 5.1.4 on 2025-10-11 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_aliases', '0003_remove_country_field'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='clientalias',
            name='client_alia_country_c8de2e_idx',
        ),
    ]
