# Generated by Django 5.1.4 on 2025-10-13 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_aliases', '0002_clientresolution'),
        ('client_aliases', '0004_remove_clientalias_client_alia_country_c8de2e_idx'),
    ]

    operations = [
    ]
