# Generated by Django 5.1.4 on 2025-10-13 11:12

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('client_aliases', '0005_merge_20251013_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientresolution',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
