# Generated by Django 5.1.4 on 2025-10-14 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_aliases', '0006_add_updated_at_to_clientresolution'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='clientresolution',
            new_name='client_reso_origina_a096a1_idx',
            old_name='client_reso_origina_idx',
        ),
        migrations.RenameIndex(
            model_name='clientresolution',
            new_name='client_reso_normali_c86154_idx',
            old_name='client_reso_normali_idx',
        ),
    ]
