# Generated by Django 5.1.4 on 2025-10-28 02:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_aliases', '0007_rename_client_reso_origina_idx_client_reso_origina_a096a1_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientalias',
            name='acepta_credito_fiscal',
            field=models.BooleanField(default=True, help_text='¿Puede recibir CCF (Comprobante Crédito Fiscal)?'),
        ),
        migrations.AddField(
            model_name='clientalias',
            name='actividad_economica',
            field=models.CharField(blank=True, help_text='Actividad económica principal del cliente', max_length=200),
        ),
        migrations.AddField(
            model_name='clientalias',
            name='aplica_retencion_iva',
            field=models.BooleanField(db_index=True, default=False, help_text='¿Este cliente retiene IVA 1%? (Gran Contribuyente)'),
        ),
        migrations.AddField(
            model_name='clientalias',
            name='aplica_retencion_renta',
            field=models.BooleanField(default=False, help_text='¿Este cliente retiene Renta?'),
        ),
        migrations.AddField(
            model_name='clientalias',
            name='direccion_fiscal',
            field=models.TextField(blank=True, help_text='Dirección fiscal del cliente'),
        ),
        migrations.AddField(
            model_name='clientalias',
            name='email_facturacion',
            field=models.EmailField(blank=True, help_text='Email para envío de facturas electrónicas', max_length=254),
        ),
        migrations.AddField(
            model_name='clientalias',
            name='nit',
            field=models.CharField(blank=True, db_index=True, help_text='NIT del cliente (El Salvador)', max_length=20),
        ),
        migrations.AddField(
            model_name='clientalias',
            name='nrc',
            field=models.CharField(blank=True, help_text='NRC del cliente (El Salvador)', max_length=20),
        ),
        migrations.AddField(
            model_name='clientalias',
            name='porcentaje_retencion_renta',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje de retención de renta (5%, 10%, etc.)', max_digits=5),
        ),
        migrations.AddField(
            model_name='clientalias',
            name='telefono',
            field=models.CharField(blank=True, help_text='Teléfono de contacto', max_length=50),
        ),
        migrations.AddField(
            model_name='clientalias',
            name='tipo_contribuyente',
            field=models.CharField(choices=[('gran_contribuyente', 'Gran Contribuyente'), ('contribuyente_normal', 'Contribuyente Normal'), ('pequeño_contribuyente', 'Pequeño Contribuyente'), ('regimen_simple', 'Régimen Simplificado'), ('no_contribuyente', 'No Contribuyente / Extranjero')], db_index=True, default='contribuyente_normal', help_text='Tipo de contribuyente según DGII El Salvador', max_length=30),
        ),
    ]
